### ISSUE TITLE
Intrusion Report Improvements

### ISSUE THREAD

**Issue by sql-sith** [sql-sith/cdc-2024#13]
- "Professionalism" was noted by judges
- Create templates

**Comment by Aksel-Rasmussen** [comment]
The main issue was the markdown compiler so I need to find a new one.

**Comment by Aksel-Rasmussen** [comment]
I will find a new one by the time it becomes relevant.

**Comment by Aksel-Rasmussen** [comment]
as for templates, that will happen at the  same time
